#!/bin/bash
# 루이스 - 스마트폰 테스트 가이드
# 사용법: bash test_on_phone.sh
set -e

echo ""
echo "========================================================"
echo "  루이스(Louis) 스마트폰 테스트 가이드"
echo "========================================================"
echo ""
echo "  STEP 1. 백엔드 시작 (이 PC에서 실행)"
echo "  ─────────────────────────────────────"
echo "  cd backend"
echo "  bash quick_start.sh"
echo ""
echo "  → PC와 스마트폰이 같은 Wi-Fi에 연결돼 있어야 해요."
echo "  → 실행 후 출력되는 '스마트폰 URL'을 복사해두세요."
echo ""
echo "  STEP 2. APK 빌드 (Flutter SDK 필요)"
echo "  ─────────────────────────────────────"
echo "  cd mobile"
echo "  bash build_test_apk.sh <STEP1에서_나온_IP>"
echo ""
echo "  예시:"
echo "  bash build_test_apk.sh 192.168.0.10"
echo ""
echo "  STEP 3. 스마트폰에 APK 설치"
echo "  ─────────────────────────────────────"
echo "  방법 A (USB): adb install build/app/outputs/flutter-apk/app-debug.apk"
echo "  방법 B (파일): APK 파일을 스마트폰으로 전송 후 직접 설치"
echo "                 (설정 > 보안 > 출처를 알 수 없는 앱 허용)"
echo ""
echo "  STEP 4. 앱 실행 및 로그인"
echo "  ─────────────────────────────────────"
echo "  아이디:   admin"
echo "  비밀번호: louis1234"
echo ""
echo "  서버 URL이 자동으로 설정돼 있어요."
echo "  연결 안 되면: 앱 > 설정 > 서버 URL 에서 직접 수정하세요."
echo ""
echo "  STEP 5. 날씨 테스트"
echo "  ─────────────────────────────────────"
echo "  채팅에서 입력: '오늘 날씨 어때?'"
echo "  날씨 + 옷차림 추천을 바로 받을 수 있어요."
echo "  (날씨는 backend/.env 에 OPENWEATHER_API_KEY 필요)"
echo ""
echo "========================================================"
echo ""
echo "  [선택] ngrok으로 외부 접속 설정 (다른 네트워크에서 테스트)"
echo "  ─────────────────────────────────────"
echo "  1. https://ngrok.com 가입 후 ngrok 설치"
echo "  2. ngrok http 8000"
echo "  3. 출력된 URL(예: https://xxxx.ngrok-free.app)로"
echo "     bash build_test_apk.sh xxxx.ngrok-free.app"
echo ""
echo "========================================================"
